import 'dotenv/config';
import { ethers } from 'ethers';
import fs from 'fs';

async function main() {
    const rpc = process.env.RPC_URL;
    const pk = process.env.PRIVATE_KEY;

    if (!rpc || !pk) {
        console.error("❌ RPC_URL atau PRIVATE_KEY belum diset!");
        process.exit(1);
    }

    const provider = new ethers.JsonRpcProvider(rpc);
    const mainWallet = new ethers.Wallet(pk, provider);

    try {
        console.log("Sending heartbeat...");
        const tx = await mainWallet.sendTransaction({ to: mainWallet.address, value: 0 });
        await tx.wait();

        // Baca dan bersihkan daftar wallet
        const data = fs.readFileSync('wallets.txt', 'utf8');
        const lines = data.split('\n').map(l => l.trim()).filter(l => l.startsWith('0x'));

        let tableRows = "";
        let totalBalance = 0;

        for (const [index, addr] of lines.entries()) {
            try {
                // Normalisasi alamat untuk menghindari Checksum Error
                const cleanAddr = ethers.getAddress(addr); 
                const balance = await provider.getBalance(cleanAddr);
                const ethBalance = parseFloat(ethers.formatEther(balance));
                totalBalance += ethBalance;
                
                const label = index === 0 ? "Main Wallet" : `Sub-Wallet ${index}`;
                tableRows += `| ${label} | \`${cleanAddr.substring(0, 10)}...${cleanAddr.substring(38)}\` | \`${ethBalance.toFixed(6)} ETH\` |\n`;
            } catch (addrErr) {
                console.warn(`⚠️ Alamat tidak valid dilewati: ${addr}`);
            }
        }

        const timestamp = new Date().toLocaleString('id-ID', { 
            timeZone: 'Asia/Jakarta',
            dateStyle: 'full',
            timeStyle: 'short'
        });

        const content = `# Indraseven's Web3 Command Center 🚀

![Status](https://img.shields.io/badge/Base_Sepolia-Active-brightgreen?style=for-the-badge&logo=base)
![Total](https://img.shields.io/badge/Total_Balance-${totalBalance.toFixed(4)}_ETH-blue?style=for-the-badge)

### 📊 Multi-Wallet Portfolio
| Label | Address | Balance (ETH) |
| :--- | :--- | :--- |
${tableRows}
| **TOTAL** | | **${totalBalance.toFixed(6)} ETH** |

### ⏱️ System Log
- **Last Update:** \`${timestamp}\`
- **Heartbeat Tx:** [\`${tx.hash.substring(0, 20)}...\`](https://sepolia.basescan.org/tx/${tx.hash})

---
*Generated by Termux & GitHub Actions.*`;

        fs.writeFileSync('README.md', content);
        console.log("✅ Dashboard updated successfully!");

    } catch (err) {
        console.error("❌ Error:", err.message);
        process.exit(1);
    }
}
main();
